baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[params]
CompanyName = 'My Hugo Site'
repoName = 'GitRepoName'

[environments.development]
baseURL = 'http://localhost:1313/'

[environments.production]
baseURL = 'https://example.org/'

